# Generated by Django 5.2.8 on 2025-12-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_branch_customuser_city_customuser_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='college_text',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
