# Generated by Django 5.2.8 on 2025-12-30 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_college_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='college',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='college_text',
        ),
    ]
