# Generated by Django 5.2 on 2026-01-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_college'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['mobile', 'otp', 'is_verified'], name='users_otp_mobile_186890_idx'),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['mobile', '-created_at'], name='users_otp_mobile_fd5236_idx'),
        ),
    ]
