# Generated by Django 5.2.8 on 2025-12-30 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_careerpath_coursebundle_assessment_result_data_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseBundle',
        ),
    ]
