# Generated by Django 5.2 on 2026-01-03 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_delete_coursebundle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerpath',
            name='required_skills',
            field=models.JSONField(blank=True, default=list, help_text='List of required skills'),
        ),
        migrations.CreateModel(
            name='CareerRequiredSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_tag', models.CharField(max_length=100)),
                ('required_level', models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='basic', max_length=20)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_requirements', to='assessments.careerpath')),
            ],
            options={
                'unique_together': {('career', 'skill_tag')},
            },
        ),
    ]
