# Generated by Django 5.2 on 2026-01-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_alter_careerpath_required_skills_careerrequiredskill'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='question_order',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
