# Generated by Django 5.2 on 2026-01-03 14:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_alter_careerpath_required_skills_careerrequiredskill'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['user', 'status'], name='assessments_user_id_1b5547_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['user', '-date_taken'], name='assessments_user_id_61f3e2_idx'),
        ),
        migrations.AddIndex(
            model_name='careerpath',
            index=models.Index(fields=['min_score'], name='assessments_min_sco_cbe432_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['category'], name='assessments_categor_22867f_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['skill_tag'], name='assessments_skill_t_5e9299_idx'),
        ),
    ]
