# Generated by Django 5.2 on 2026-01-26 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_assessment_question_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='date_taken',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='status',
            field=models.CharField(db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('psychometric', 'Psychometric'), ('aptitude', 'Aptitude'), ('technical', 'Technical')], db_index=True, default='technical', max_length=20),
        ),
    ]
