# Generated by Django 5.2 on 2026-01-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='short_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='college',
            name='short_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='college',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
