# Generated by Django 5.2 on 2026-01-03 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_branch_short_name_college_short_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_states', to='core.city')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_states', to='core.state')),
            ],
        ),
    ]
