# Generated by Django 5.2 on 2026-01-03 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_city_state_alter_citystate_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='state',
        ),
    ]
