# Generated by Django 5.2 on 2026-01-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_city_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='name',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['name'], name='core_branch_name_5a8f35_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['name'], name='core_city_name_079295_idx'),
        ),
        migrations.AddIndex(
            model_name='citystate',
            index=models.Index(fields=['state'], name='core_cityst_state_i_ce6d02_idx'),
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['name'], name='core_colleg_name_01a29b_idx'),
        ),
        migrations.AddIndex(
            model_name='state',
            index=models.Index(fields=['name'], name='core_state_name_bf6f8a_idx'),
        ),
    ]
