# Generated by Django 5.2 on 2026-01-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_city_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Arts/Commerce', 'Arts/Commerce'), ('Engineering', 'Engineering')], max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='college',
            name='name',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
