# Generated by Django 5.2 on 2026-01-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_degree_alter_college_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degree',
            name='category',
            field=models.CharField(choices=[('Arts & Humanities', 'Arts & Humanities'), ('Commerce & Management', 'Commerce & Management'), ('Science', 'Science'), ('Engineering & Technology', 'Engineering & Technology'), ('Computer & IT', 'Computer & IT'), ('Education', 'Education'), ('Law', 'Law'), ('Medical & Health Sciences', 'Medical & Health Sciences'), ('Pharmacy', 'Pharmacy'), ('Design & Architecture', 'Design & Architecture'), ('Journalism & Media', 'Journalism & Media'), ('Social Work', 'Social Work'), ('Agriculture & Allied Sciences', 'Agriculture & Allied Sciences'), ('Vocational & Diploma', 'Vocational & Diploma'), ('Research & Doctorate', 'Research & Doctorate')], max_length=50),
        ),
    ]
