# Generated by Django 5.2 on 2026-01-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_degree_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='degree',
            name='is_tech',
            field=models.BooleanField(default=False),
        ),
    ]
