# Generated by Django 5.2 on 2026-01-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_degree_is_tech'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(db_index=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='college',
            name='name',
            field=models.CharField(db_index=True, default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='degree',
            name='full_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='degree',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
