# Generated by Django 5.2.8 on 2025-12-22 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='ideal_for',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='course',
            name='job_roles',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(default='Beginner', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='original_price_inr',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='course',
            name='programs_included',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='course',
            name='short_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
