# Generated by Django 5.2 on 2026-01-03 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_enrollment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseskill',
            name='coverage_level',
            field=models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='basic', max_length=20),
        ),
        migrations.AlterField(
            model_name='courseskill',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='courses.course'),
        ),
        migrations.AlterUniqueTogether(
            name='courseskill',
            unique_together={('course', 'skill_tag')},
        ),
    ]
