# Generated by Django 5.2 on 2026-01-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_degree_alter_college_name'),
        ('courses', '0006_courseskill_coverage_level_alter_courseskill_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_title', models.CharField(max_length=255)),
                ('skills_required', models.TextField()),
                ('duration', models.CharField(max_length=50)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('next_batch_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('degrees', models.ManyToManyField(related_name='course_bundles', to='core.degree')),
            ],
        ),
    ]
