# Generated by Django 5.2 on 2026-01-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_coursebundle'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursebundle',
            name='initial_salary',
            field=models.IntegerField(default=0),
        ),
    ]
