# Generated by Django 5.2 on 2026-01-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_coursebundle_initial_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='course',
            name='ideal_for',
        ),
        migrations.RemoveField(
            model_name='course',
            name='job_roles',
        ),
        migrations.RemoveField(
            model_name='course',
            name='language',
        ),
        migrations.RemoveField(
            model_name='course',
            name='level',
        ),
        migrations.RemoveField(
            model_name='course',
            name='original_price_inr',
        ),
        migrations.RemoveField(
            model_name='course',
            name='price',
        ),
        migrations.RemoveField(
            model_name='course',
            name='programs_included',
        ),
        migrations.RemoveField(
            model_name='course',
            name='short_description',
        ),
        migrations.AddField(
            model_name='coursebundle',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='CourseSkill',
        ),
    ]
