# Generated by Django 5.2 on 2026-01-25 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_remove_course_description_remove_course_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.coursebundle'),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
